export const INCREMENT_CART_ITEM_COUNT = 'INCREMENT_CART_ITEM_COUNT';
export const ASSIGN_CART_ITEM_COUNT = 'ASSIGN_CART_ITEM_COUNT';
export const SET_CART_ITEMS = 'SET_CART_ITEMS';
export const CLEAR_CART = 'CLEAR_CART';


export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN';
export const CLEAR_AUTH_TOKEN = 'CLEAR_AUTH_TOKEN';


// actionTypes.js
export const FETCH_RESTAURANTS_SUCCESS = 'FETCH_RESTAURANTS_SUCCESS';
export const FETCH_RESTAURANT_DETAILS_SUCCESS = 'FETCH_RESTAURANT_DETAILS_SUCCESS';
export const FETCH_RESTAURANT_MENU_SUCCESS = 'FETCH_RESTAURANT_MENU_SUCCESS';

export const FETCH_RESTAURANTS_FAILURE = 'FETCH_RESTAURANTS_FAILURE';
export const FETCH_RESTAURANT_DETAILS_FAILURE = 'FETCH_RESTAURANT_DETAILS_FAILURE';
export const FETCH_RESTAURANT_MENU_FAILURE = 'FETCH_RESTAURANT_MENU_FAILURE';


export const SET_ORDER_STATUS = 'SET_ORDER_STATUS';